### PR TITLE
function check using operation.constructor.name is not supported in I…

### PR DESCRIPTION
**Pull request by kovcic**
…E (11, 10, ?)

### CODE REVIEW

**Comment by kovcic** [comment]
maybe to have custom isFunction that would cover all cases, e.g. like one from lodash lib

**Comment by abacaj** [comment]
Hey @kovcic thanks for the pull request, this looks good.

What do you think of using the isFunction from here: https://github.com/arasatasaygin/is.js/blob/master/is.js#L144

**Comment by kovcic** [comment]
@abacaj I agree, updated

**Comment by abacaj** [comment]
Good stuff, I've added you as a contributor @kovcic 😄

**Pull request merged**
